AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Enabled: false # 行の長さ制限を無効化

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false # コメントを必須としない
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

require:
  - rubocop-rails
  - rubocop-rspec


RSpec:
  Enabled: true
